
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-09T19:22:04+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ce4906df19185b8b73bfa18989e64315309d2bb5",
 "version": "v2.0.0-1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
