name: CI - Build and Test

defaults:
  run:
    shell: bash

on: [pull_request, workflow_dispatch]

jobs:

  build:
    name: Check package
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - 'ubuntu-latest'
          #- 'macos-latest'
          #- 'windows-latest'
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{matrix.python-version}}
          architecture: x64
      - name: Init Template
        env:
          python_version: ${{matrix.python-version}}
        run: |
          cd bin
          echo -e "${python_version}\nTEMPLATE\nsrc\nBasic Template\nn" | bash init_repo.sh
      - name: Compile Requirements
        run: |
          make reqs
      - name: Install
        run: |
          pip install -e .
          pip install -r requirements/requirements_ci.txt
      - name: Check typing, linting and formatting
        run: |
          make checks
      - name: Run tests
        run: pytest
      - name: Make documentation
        run: make --directory=sphinx --file=Makefile html