name: CI - Build and Test

defaults:
  run:
    shell: bash

on: [pull_request, workflow_dispatch]

jobs:

  build:
    name: Check package
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - 'ubuntu-latest'
          #- 'macos-latest'
          #- 'windows-latest'
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{matrix.python-version}}
          architecture: x64

      - name: Check typing, linting and formatting
        run: make checks

      - name: Make documentation
        run: make docs
